# .github/workflows/auto-release.yml
name: Nightly Build

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate version
        id: version
        run: |
          # Get base version from gradle.properties
          BASE_VERSION=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          # Get commit count
          COMMIT_COUNT=$(git rev-list --count HEAD)
          # Create full version string
          VERSION="${BASE_VERSION}-nightly-${COMMIT_COUNT}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version will be: $VERSION"
          
          # Update gradle.properties with new version
          sed -i "s/mod_version=.*/mod_version=$VERSION/" gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Automatic release from main branch
            Commit: ${{ github.sha }}
          draft: false
          prerelease: true  # Set to true since it's alpha
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add gradle.properties
          git commit -m "Update version to ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push
